---
- name: Create directories for capistrano deployment
  file:
    dest: '~/www/rails/{{ item.name }}/shared/config'
    state: directory
  with_items: '{{ rails_apps }}'

- name: Create MySQL database(s)
  mysql_db:
    name: "{{ ansible_user }}_{{ item.name }}"
    collation: utf8_unicode_ci
    encoding: utf8
    state: present
  with_items: '{{ rails_apps }}'

- name: Read MySQL database password from ~/.my.cnf
  shell: sed -n -e '/\[client\]/,$p' ~/.my.cnf | grep password | head -1 | cut -d= -f2 | cut -d " " -f1 warn=no
  register: database_password
  changed_when: False

- name: Create database.yml
  template:
    src : templates/database.yml.j2
    dest: '~/www/rails/{{ item.name }}/shared/config/database.yml'
  with_items: '{{ rails_apps }}'

- name: Create daemontools jobs for unicorns
  shell: 'uberspace-setup-service rails-app-{{ item.name }} bundle exec unicorn --host 127.0.0.1 --port {{ item.port }}'
  args:
    creates: '~/etc/run-rails-app-{{ item.name }}/run'
  with_items: '{{ rails_apps }}'

- name: Configure daemontools jobs for rails
  blockinfile:
  args:
    dest: '~/etc/run-rails-app-{{ item.name }}/run'
    insertbefore: '^exec'
    block: |
      export RAILS_ENV=production
      export RAILS_SERVE_STATIC_FILES=true
      export SECRET_KEY_BASE={{ item.secret_key_base }}
      cd ~/www/rails/{{ item.name }}/current
  with_items: '{{ rails_apps }}'

- name: Create web directory for rails apps
  file:
    path: '/var/www/virtual/{{ ansible_user }}/rails/{{ item.name }}/web'
    state: directory
  with_items: '{{ rails_apps }}'

- name: Set up .htaccess for Rails apps and redirect all traffic to main domain
  blockinfile:
    dest: '/var/www/virtual/{{ ansible_user }}/rails/{{ item.name }}/web/.htaccess'
    create: yes
    insertbefore: BOF
    block: |
      RewriteEngine On
      RewriteCond %{HTTP_HOST} !={{ item.domains[0] }}
      RewriteRule (.*) https://{{ item.domains[0] }}/$1 [R=301,L]
      RewriteRule (.*) http://localhost:{{ item.port }}/$1 [P]
  with_items: '{{ rails_apps }}'

- name: Create domain symlinks for rails apps
  file:
    dest: /var/www/virtual/{{ ansible_user }}/{{ item.1 }}
    src: /var/www/virtual/{{ ansible_user }}/rails/{{ item.0.name }}/web
    state: link
  with_subelements:
    - "{{ rails_apps }}"
    - domains
