---
#- name: Upload local user's public key for SSH
#  authorized_key:
#    user: "{{ ansible_env.USER }}"
#    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Generate SSH key pair for remote user on Uberspace
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa

#- name: Fetch remote user's public key (e.g. for Git access)
#  fetch:
#    src: ~/.ssh/id_rsa.pub
#    dest: "public_keys/{{ ansible_host }}"
#    flat: yes

#- name: Configure Git
#  template:
#    src: templates/gitconfig.j2
#    dest: ~/.gitconfig

- name: Add domains
  include_tasks: domains.yml
  with_items: "{{ domains }}"
  when: domains is defined
