---
- name: Upload local user's public key for SSH
  authorized_key:
    user: "{{ansible_user}}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Generate SSH key pair for remote user on Uberspace
  user: name={{ ansible_user }} generate_ssh_key=yes ssh_key_bits=4096 ssh_key_file=.ssh/id_rsa

- name: Fetch remote user's public key (e.g. for Git access)
  fetch: src=~/.ssh/id_rsa.pub dest=public_keys/{{ ansible_host }} flat=yes

- name: Configure Git
  template:
    src: templates/gitconfig.j2
    dest: ~/.gitconfig

- name: Run uberspace-add-domain
  shell: uberspace-add-domain -w -d {{item}}
  with_items: '{{ domains }}'
  ignore_errors: yes

- name: Enable Strict Transport Security
  shell: uberspace-configure-webserver enable hsts
  register: result
  changed_when: "'new configuration will be live' in result.stdout"

- name: Enable daemontools
  shell: uberspace-setup-svscan
  args:
    creates: ~/service

- name: Create ~/www symlink
  file:
    path: ~/www
    src: /var/www/virtual/{{ ansible_user }}/
    state: link
